# Generated by Django 3.1.1 on 2021-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnword',
            name='synonym',
        ),
        migrations.AddField(
            model_name='learnword',
            name='synonym',
            field=models.ManyToManyField(related_name='synonyms', to='board.Synonym'),
        ),
    ]
