# Generated by Django 3.1.1 on 2021-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210730_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnword',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
