# Generated by Django 3.1.1 on 2021-08-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210731_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnword',
            name='definition',
            field=models.CharField(default=1312, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnword',
            name='part_of_speech',
            field=models.CharField(default=2131, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnword',
            name='synonyms',
            field=models.CharField(default=312, max_length=255),
            preserve_default=False,
        ),
    ]
