# Generated by Django 3.1.1 on 2021-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210802_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnword',
            name='example',
            field=models.CharField(default=1231233, max_length=255),
            preserve_default=False,
        ),
    ]
