# Generated by Django 3.1.1 on 2021-08-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_learnword_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnword',
            old_name='definition',
            new_name='translation',
        ),
        migrations.RemoveField(
            model_name='learnword',
            name='example',
        ),
        migrations.RemoveField(
            model_name='learnword',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='learnword',
            name='synonyms',
        ),
    ]
