# Generated by Django 3.1.1 on 2021-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210802_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnword',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
